# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_test_action: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        npm install
        npm run all

  test_action_and_deploy_demo: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: 'Deploy demo app using action'
      uses: ./
      with:
        run_lint: true
        github_access_token: ${{ secrets.ACCESS_TOKEN }}
        build_configuration: # The branch the action should deploy from.
        base_href: /src
        deploy_branch: master # The branch the action should deploy to.
        angular_dist_build_folder: src/dist/shopping # The folder the action should deploy.
        angular_project_dir: src